name: "Delete CloudFormation Stack"

on: 
  workflow_dispatch:


permissions:
  id-token: write # This is required for aws oidc connection
  contents: read # This is required for actions/checkout
  pull-requests: write # This is required for gh bot to comment PR  

jobs:
  _1-devl:
    uses: subhamay-gh-actions/cfdelete/.github/workflows/cf-delete.yaml@v1
    with:
      github_env: devl
    secrets:
      aws_region: ${{ secrets.AWS_REGION }}
      aws_role_arn: ${{ secrets.DEVL_AWS_ROLE_ARN }}
      code_repository_s3_bucket: ${{ secrets.DEVL_CODE_REPOSITORY_S3_BUCKET }}
  _2-test:
    needs: [_1-devl ]
    uses: subhamay-gh-actions/cfdelete/.github/workflows/cf-delete.yaml@v1
    with:
      github_env: test
    secrets:
      aws_region: ${{ secrets.AWS_REGION }}
      aws_role_arn: ${{ secrets.TEST_AWS_ROLE_ARN }}
      code_repository_s3_bucket: ${{ secrets.TEST_CODE_REPOSITORY_S3_BUCKET }}
  _3-prod:
    needs: [ _2-test ]
    uses: subhamay-gh-actions/cfdelete/.github/workflows/cf-delete.yaml@v1
    with:
      github_env: prod
    secrets:
      aws_region: ${{ secrets.AWS_REGION }}
      aws_role_arn: ${{ secrets.PROD_AWS_ROLE_ARN }}
      code_repository_s3_bucket: ${{ secrets.PROD_CODE_REPOSITORY_S3_BUCKET }}
